"""SQLAlchemy models. Import every model module here so Alembic sees all tables."""

from .base import Base
from .claims import (
    ClaimCase,
    ClaimEvidenceEntry,
    FormA,
    FormAClaimItem,
    FormAFamilyMember,
    FormB,
    FormBRightClaim,
    FormC,
    FormCBorderingVillage,
    FormCLandmark,
    WorkflowEvent,
)
from .enums import (
    DISTRICT_ROLES,
    BoundarySide,
    CaseState,
    ClaimType,
    ConsolidationStatus,
    EvidenceKind,
    EvidenceRule,
    FormAClaim,
    FormBRight,
    Gender,
    LandmarkKind,
    LetterTemplate,
    MemberCategory,
    Role,
    WorkflowAction,
)
from .people import AppUser, GramSabha, GsMember, UserRole, Village
from .procedure import (
    CaseClaimant,
    ClaimCall,
    Correspondence,
    Evidence,
    EvidenceVerification,
    Frc,
    FrcMember,
    LedgerEntry,
    Media,
    Recusal,
)

__all__ = [
    "DISTRICT_ROLES",
    "AppUser",
    "Base",
    "BoundarySide",
    "CaseClaimant",
    "CaseState",
    "ClaimCall",
    "ClaimCase",
    "ClaimEvidenceEntry",
    "ClaimType",
    "ConsolidationStatus",
    "Correspondence",
    "Evidence",
    "EvidenceKind",
    "EvidenceRule",
    "EvidenceVerification",
    "FormA",
    "FormAClaim",
    "FormAClaimItem",
    "FormAFamilyMember",
    "FormB",
    "FormBRight",
    "FormBRightClaim",
    "FormC",
    "FormCBorderingVillage",
    "FormCLandmark",
    "Frc",
    "FrcMember",
    "Gender",
    "GramSabha",
    "GsMember",
    "LandmarkKind",
    "LedgerEntry",
    "LetterTemplate",
    "Media",
    "MemberCategory",
    "Recusal",
    "Role",
    "UserRole",
    "Village",
    "WorkflowAction",
    "WorkflowEvent",
]
