"""SQLAlchemy models. Import every model module here so Alembic sees all tables."""

from .base import Base
from .claims import (
    ClaimCase,
    ClaimEvidenceEntry,
    FormA,
    FormAClaimItem,
    FormAFamilyMember,
    FormB,
    FormBRightClaim,
    FormC,
    FormCBorderingVillage,
    FormCLandmark,
    WorkflowEvent,
)
from .enums import (
    DISTRICT_ROLES,
    BoundarySide,
    CaseState,
    ClaimType,
    ConsolidationStatus,
    EvidenceRule,
    FormAClaim,
    FormBRight,
    Gender,
    LandmarkKind,
    MemberCategory,
    Role,
    WorkflowAction,
)
from .people import AppUser, GramSabha, GsMember, UserRole, Village
from .procedure import CaseClaimant, Frc, FrcMember, Recusal

__all__ = [
    "DISTRICT_ROLES",
    "AppUser",
    "Base",
    "BoundarySide",
    "CaseClaimant",
    "CaseState",
    "ClaimCase",
    "ClaimEvidenceEntry",
    "ClaimType",
    "ConsolidationStatus",
    "EvidenceRule",
    "FormA",
    "FormAClaim",
    "FormAClaimItem",
    "FormAFamilyMember",
    "FormB",
    "FormBRight",
    "FormBRightClaim",
    "FormC",
    "FormCBorderingVillage",
    "FormCLandmark",
    "Frc",
    "FrcMember",
    "Gender",
    "GramSabha",
    "GsMember",
    "LandmarkKind",
    "MemberCategory",
    "Recusal",
    "Role",
    "UserRole",
    "Village",
    "WorkflowAction",
    "WorkflowEvent",
]
