"""Stored records (MongoDB documents) and the vocabularies they use."""

from .base import Doc, Part, TimestampedDoc, new_id, now_ms
from .boundary import (
    BoundaryLandmark,
    BoundarySegment,
    BoundaryWalk,
    CfrBoundary,
    Dispute,
    UseZone,
)
from .claims import (
    ClaimCase,
    ClaimEvidenceEntry,
    FormA,
    FormAClaimItem,
    FormAFamilyMember,
    FormB,
    FormBRightClaim,
    FormC,
    FormCBorderingVillage,
    FormCLandmark,
    WorkflowEvent,
)
from .enums import (
    BoundarySide,
    BoundaryStatus,
    CaseState,
    ClaimType,
    ConsolidationStatus,
    DisputeOutcome,
    EvidenceKind,
    EvidenceRule,
    FormAClaim,
    FormBRight,
    Gender,
    LandmarkKind,
    LetterTemplate,
    MemberCategory,
    Role,
    UseZoneType,
    WorkflowAction,
)
from .notifications import DeviceToken, Notification
from .people import AppUser, GramSabha, GsMember, UserRole, Village
from .procedure import (
    Attendance,
    CaseClaimant,
    ClaimCall,
    Correspondence,
    Evidence,
    EvidenceVerification,
    Frc,
    FrcMember,
    GsMeeting,
    LedgerEntry,
    Media,
    Recusal,
    Resolution,
    TitleFollowup,
    VerificationProceeding,
)

# Every kind of record stored on its own, by collection name (used by the hash chain to
# load a chained record, and by the database setup).
DOC_TYPES: dict[str, type[Doc]] = {
    m.COLLECTION: m
    for m in (
        Village,
        GramSabha,
        GsMember,
        AppUser,
        UserRole,
        ClaimCase,
        WorkflowEvent,
        Frc,
        CaseClaimant,
        Recusal,
        ClaimCall,
        Media,
        Evidence,
        EvidenceVerification,
        LedgerEntry,
        Correspondence,
        VerificationProceeding,
        GsMeeting,
        Resolution,
        TitleFollowup,
        CfrBoundary,
        BoundaryWalk,
        Dispute,
        Notification,
        DeviceToken,
    )
}

__all__ = [
    "DOC_TYPES",
    "AppUser",
    "Attendance",
    "BoundaryLandmark",
    "BoundarySegment",
    "BoundarySide",
    "BoundaryStatus",
    "BoundaryWalk",
    "CaseClaimant",
    "CaseState",
    "CfrBoundary",
    "ClaimCall",
    "ClaimCase",
    "ClaimEvidenceEntry",
    "ClaimType",
    "ConsolidationStatus",
    "Correspondence",
    "DeviceToken",
    "Dispute",
    "DisputeOutcome",
    "Doc",
    "Evidence",
    "EvidenceKind",
    "EvidenceRule",
    "EvidenceVerification",
    "FormA",
    "FormAClaim",
    "FormAClaimItem",
    "FormAFamilyMember",
    "FormB",
    "FormBRight",
    "FormBRightClaim",
    "FormC",
    "FormCBorderingVillage",
    "FormCLandmark",
    "Frc",
    "FrcMember",
    "Gender",
    "GramSabha",
    "GsMeeting",
    "GsMember",
    "LandmarkKind",
    "LedgerEntry",
    "LetterTemplate",
    "Media",
    "MemberCategory",
    "Notification",
    "Part",
    "Recusal",
    "Resolution",
    "Role",
    "TimestampedDoc",
    "TitleFollowup",
    "UseZone",
    "UseZoneType",
    "UserRole",
    "VerificationProceeding",
    "Village",
    "WorkflowAction",
    "WorkflowEvent",
    "new_id",
    "now_ms",
]
