import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'language_title': 'Choose Your Language',
      'language_subtitle': 'Select your preferred language',
      'btn_continue': 'Continue →',
      'login_title': 'Sign In',
      'login_subtitle': 'Sign In to VanMitra-AI',
      'label_name': 'Your Name',
      'hint_name': 'Enter your full name',
      'label_phone': 'Mobile Number',
      'hint_phone': '10-digit mobile number',
      'label_role': 'Select Role',
      'role_villager': 'Villager (ग्रामस्थ)',
      'role_admin': 'Gram Panchayat (ग्रामपंचायत)',
      'label_village': 'Select Village',
      'btn_send_otp': 'Send OTP →',
      'label_otp': 'OTP Code',
      'btn_verify': 'Verify & Continue →',
      'legal_notice': 'Your data is stored locally on your device. No personal information is shared without your consent.',
      'claim_nature_cultivation': 'Cultivation',
      'claim_nature_habitation': 'Habitation',
      'claim_nature_mfpCollection': 'MFP Collection',
      'claim_nature_grazing': 'Grazing',
      'claim_nature_waterBodies': 'Water Bodies',
      'claim_nature_traditionalResource': 'Traditional Resource',
      'claim_nature_other': 'Other',
      // Dashboard & Tabs
      'tab_dashboard': 'Dashboard',
      'tab_claims': 'Claims',
      'tab_gramsabha': 'Gram Sabha',
      'tab_map': 'Map',
      'tab_profile': 'Profile',
      'tab_upcoming': 'Upcoming',
      'tab_past': 'Past',
      // Actions
      'action_new_claim': 'File New Claim',
      'action_track_claim': 'Track My Claims',
      'action_schedule_meeting': 'Schedule Meeting',
      'action_post_notice': 'Post Notice',
      'action_attendance': 'Attendance',
      'action_record_resolution': 'Record Resolution',
      'action_verify_chain': 'Verify Chain',
      'action_review_claims': 'Review Claims',
      'action_map_monitor': 'Boundary Map',
      // Claims
      'title_new_claim': 'New Claim',
      'title_draft_preview': 'Draft Preview',
      'title_evidence_checklist': 'Evidence Checklist',
      'title_appeal_draft': 'Appeal Draft',
      'title_rejection_analysis': 'Rejection Analysis',
      'title_my_claims': 'My Claims',
      'btn_next_draft': 'Next — Generate Draft',
      'btn_submit_claim': 'Submit Claim',
      'msg_draft_saved': '✅ Draft Saved',
      'msg_ai_generating': 'AI is generating draft...',
      'claim_status_draft': 'Draft',
      'claim_status_submitted': 'Submitted',
      'claim_status_under_review': 'Under Review',
      'claim_status_approved': 'Approved',
      'claim_status_appeal': 'Appeal Filed',
      // Common Home Keys
      'welcome': 'Hello',
      'villager': 'Villager',
      'approved_claims': 'Approved Claims',
      'hectares': 'Hectares Area',
      'meeting_records': 'Meeting Records',
      'claims': 'Claims',
      'action_new_claim_sub': 'Submit new individual or community claim',
      'coming_soon': 'Coming Soon',
      'action_evidence_checklist': 'Evidence Checklist (Rule 13)',
      'action_evidence_checklist_sub': 'View required documents and evidence',
      'gram_sabha': 'Gram Sabha',
      'action_view_records': 'View Gram Sabha Records',
      'action_view_records_sub': 'View Gram Sabha Records & Ledger',
      'action_self_checkin': 'Self Check-in',
      'action_self_checkin_sub': 'Mark attendance for ongoing meeting',
      'select_active_meeting_first': 'Please select an active meeting from the dashboard first.',
      'action_map': 'Forest Boundary Map',
      'action_map_sub': 'View Forest Boundary Map',
      'action_know_rights': 'Know Your Rights (FRA)',
      'action_know_rights_sub': 'Know Your Rights — Forest Rights Act',
      'todays_meeting': 'Today\'s Meeting',
      'next_meeting': 'Next Meeting',
      'venue': 'Venue',
      'mark_attendance': 'Mark My Attendance →',
      'no_meeting_scheduled': 'No meetings scheduled',
      'admin_welcome': 'VanMitra Admin',
      'admin_subtitle': 'Gram Sabha Administrator',
      'total_claims': 'Total Claims',
      'meetings': 'Meetings',
      'resolutions': 'Resolutions',
      'members': 'Members',
      // My Claims Screen
      'search_claim_hint': 'Search by Claim ID...',
      'filter_all': 'All',
      'filter_approved': 'Approved',
      'filter_pending': 'Pending',
      'filter_rejected': 'Rejected',
      'claims_count_suffix': 'Claims',
      'appeal_deadline': 'Appeal Deadline',
      'days_left': 'days left',
      'appeal_now': 'Appeal Now →',
      'application_no': 'Application No.',
      'survey_no': 'Survey',
      'sq_meters': 'Sq.m.',
      'date_prefix': 'Date',
      'step_received': 'Received',
      'step_verification': 'Verify',
      'step_gramsabha': 'GS',
      'step_decision': 'Decision',
      'no_claims_filter': 'No claims match this filter.',
      'no_claims_yet': 'No claims submitted yet.',
      'search_placeholder': 'Search by application ID or claimant',
      'error_loading_claims': 'Unable to load claims. Please check your connection and try again.',
      // Claim Type Screen
      'claim_type': 'Claim Type',
      'eligibility_check': 'Eligibility Check (FRA Sec. 2)',
      'st_question': 'Do you belong to a Scheduled Tribe (ST)?',
      'yes': 'Yes',
      'no': 'No',
      'residence_year': 'Year when residence/cultivation began on the land:',
      'date_hint': 'e.g. 1995-01-01 (YYYY-MM-DD)',
      'eligible_fdst': '✅ Eligible — FDST (Scheduled Tribe) Category',
      'eligible_otfd': '✅ Eligible — OTFD Category',
      'not_eligible': '❌ Must be resident before 13 Dec 2005.',
      'select_claim_type': 'Select Claim Type',
      'select_claim_type_sub': 'Select the type of claim you want to file',
      'form_a_desc': 'Individual Forest Right under FRA Sec. 3(1)(a) or Community Rights under Sec. 3(1)(b-d).',
      'form_b_desc': 'Community Forest Resource (CFR) under FRA Sec. 3(1)(i). Filed by Gram Sabha.',
      'fra_info': 'Refer to Forest Rights Act 2006 to know which form to fill.',
      'recommended': 'Recommended',
      // Evidence Checklist Screen
      'breadcrumbs_evidence': 'Evidence',
      'upload_offline_error': 'Offline — upload later.',
      'upload_verified': '✅ Verified!',
      'upload_review': '⚠️ Needs Review',
      'upload_rejected': '❌ Rejected — Try again',
      'match': 'match',
      'evidence_category': 'Evidence Category',
      'evidence_weight': 'Weight',
      'evidence_status': 'Status',
      'evidence_unverified': 'Unverified',
      'evidence_rule_13_note': 'Rule 13 (FRA Rules 2008): Oral evidence, statement of elders, and community verification are accepted.',
      'btn_next_incomplete': 'Next — Incomplete Evidence',
      'btn_more_evidence_needed': 'More Evidence Needed',
      // Evidence Gauge
      'evidence_ready': '🟢 Ready — Submit',
      'evidence_partial': '🟡 Partial — Add Evidence',
      'evidence_risk': '🔴 High Risk — Contact FRC',
      'evidence_score_label': 'Evidence Score (E = Σwᵢ·xᵢ)',
      'evidence_submitted': 'evidence submitted',
      'evidence_upload_pending': '🔘 Pending Upload',
      'evidence_btn_upload': 'Upload',
      'evidence_verified_chip': '✅ Verified',
      'evidence_review_chip': '⚠️ Review',
      'evidence_rejected_chip': '❌ Rejected',
      // Evidence Categories
      'ev_cat_government_records': 'Government Records (Voter ID, Ration Card, land records)',
      'ev_cat_physical_structures': 'Physical Structures (wells, bunds, houses on land)',
      'ev_cat_satellite_imagery': 'Satellite/Aerial Imagery',
      'ev_cat_elder_statements': 'Statements of Elders (at least 2 neighbours)',
      'ev_cat_traditional_structures': 'Traditional Community Structures (sacred groves, burial sites)',
      'ev_cat_other_govt_schemes': 'Other Government Scheme Evidence (MGNREGA job card)',
      'ev_desc_government_records': 'Any official government registry proving existence or residence prior to December 13, 2005.',
      'ev_desc_physical_structures': 'Proof of physical or agricultural improvements made on the claimed land.',
      'ev_desc_satellite_imagery': 'Visual proof showing historical cultivation or occupation of the land.',
      'ev_desc_elder_statements': 'Statements from at least 2 village elders or neighbors verifying the claimant\'s long-term occupation.',
      'ev_desc_traditional_structures': 'Proof of traditional community landmarks on or near the land.',
      'ev_desc_other_govt_schemes': 'Proof of government scheme enrollments tied to the claimant and the land.',
      'rule13_title': 'Rule 13 Evidence Checklist',
      'rule13_subtitle': 'Based on Forest Rights Act (FRA) Rule 13, claimants must provide a combination of these documents to build an "Evidence Completeness Score". A score of 80% or more is required for Gram Sabha approval.',
      'rule13_official_link': 'View Official FRA Guidelines',
      // Portal
      'footer_text': 'Helpline: 1800-209-6060 | Forest Rights Act 2006 | Privacy Policy',
      'app_title': 'VanMitra-AI | VanMitra',
      'default_village_name': 'Ozhar Grampanchayat, Jawhar',
      // Claim Form Screen
      'step_1_claimant': '① Claimant',
      'step_2_land': '② Land',
      'step_3_occupancy': '③ Occupancy',
      'step_4_evidence': '④ Evidence',
      'step_5_review': '⑤ Review',
      'draft_saved': '✅ Draft Saved',
      'form_a_title': 'Form A — Individual Claim',
      'form_b_title': 'Form B — Community Claim',
      'section_claimant_info': 'Claimant Information',
      'section_land_details': 'Land Details',
      'section_occupancy_details': 'Occupation Details',
      'section_upload_evidence': 'Upload Evidence',
      'label_claimant_name': 'Claimant Name *',
      'hint_claimant_name': 'Full Name',
      'label_father_name': 'Father\'s / Husband\'s Name *',
      'hint_father_name': 'Father\'s / Husband\'s Name',
      'label_address': 'Address *',
      'hint_address': 'Village, Taluka, District',
      'info_auto_fill': 'Jawhar Taluka, Palghar District will be auto-filled.',
      'label_survey_no': 'Survey / Gat Number',
      'hint_survey_no': 'e.g. 123/4A',
      'label_area': 'Area (sq.m.) *',
      'hint_area': 'e.g. 1200',
      'label_nature_of_claim': 'Nature of Right *',
      'label_years_occupied': 'Years of Occupation *',
      'hint_years_occupied': 'e.g. 30',
      'label_before_2005': 'Occupied before 13 Dec 2005 (FRA condition)',
      'label_land_description': 'Land Description',
      'hint_land_description': 'Usage, boundaries, landmarks',
      'fra_2005_warning': 'As per FRA 2006, occupation before 13 Dec 2005 is mandatory.',
      'evidence_upload_instruction': 'Upload all 6 evidence categories on the next screen and perform AI verification.',
      'btn_go_to_evidence': 'Go to Evidence Verification Screen',
      'section_review_submit': 'Review & Submit',
      'review_submit_desc': 'Review the AI-generated draft. Once approved, it will be submitted to the Gram Sabha.',
      'btn_preview_draft': 'Preview Draft',
      'btn_save': 'Save',
      'btn_back': 'Back',
      'btn_next': 'Next',
    },
    'mr': {
      'language_title': 'भाषा निवडा',
      'language_subtitle': 'तुमची पसंतीची भाषा निवडा',
      'btn_continue': 'पुढे जा →',
      'login_title': 'प्रवेश करा',
      'login_subtitle': 'VanMitra-AI मध्ये प्रवेश करा',
      'label_name': 'आपले नाव',
      'hint_name': 'तुमचे पूर्ण नाव प्रविष्ट करा',
      'label_phone': 'मोबाईल नंबर',
      'hint_phone': '१० अंकी मोबाईल नंबर',
      'label_role': 'भूमिका निवडा',
      'role_villager': 'ग्रामस्थ (Villager)',
      'role_admin': 'ग्रामपंचायत (Admin)',
      'label_village': 'गाव निवडा',
      'btn_send_otp': 'OTP पाठवा →',
      'label_otp': 'OTP कोड',
      'btn_verify': 'पडताळणी करा आणि पुढे जा →',
      'legal_notice': 'तुमचा डेटा तुमच्या डिव्हाइसवर स्थानिक पातळीवर जतन केला जातो. तुमच्या संमतीशिवाय कोणतीही वैयक्तिक माहिती सामायिक केली जात नाही.',
      'claim_nature_cultivation': 'शेती',
      'claim_nature_habitation': 'निवास',
      'claim_nature_mfpCollection': 'गौण वनोपज संकलन',
      'claim_nature_grazing': 'चराई',
      'claim_nature_waterBodies': 'जलस्रोत',
      'claim_nature_traditionalResource': 'पारंपरिक संसाधन',
      'claim_nature_other': 'इतर',
      // Dashboard & Tabs
      'tab_dashboard': 'डॅशबोर्ड',
      'tab_claims': 'दावे',
      'tab_gramsabha': 'ग्रामसभा',
      'tab_map': 'नकाशा',
      'tab_profile': 'प्रोफाइल',
      'tab_upcoming': 'येणारी (Upcoming)',
      'tab_past': 'मागील (Past)',
      // Actions
      'action_new_claim': 'नवीन दावा दाखल करा',
      'action_track_claim': 'माझे दावे ट्रॅक करा',
      'action_schedule_meeting': 'नवीन ग्रामसभा तयार करा',
      'action_post_notice': 'सूचना पोस्ट करा',
      'action_attendance': 'उपस्थिती व्यवस्थापन',
      'action_record_resolution': 'ठराव नोंदवा',
      'action_verify_chain': 'हॅश चेन पडताळणी',
      'action_review_claims': 'दावे पुनरावलोकन',
      'action_map_monitor': 'सीमा निरीक्षण',
      // Claims
      'title_new_claim': 'नवीन दावा',
      'title_draft_preview': 'मसुदा पूर्वावलोकन',
      'title_evidence_checklist': 'पुरावा तपासणी',
      'title_appeal_draft': 'अपील मसुदा',
      'title_rejection_analysis': 'नामंजूर विश्लेषण',
      'title_my_claims': 'माझे दावे',
      'btn_next_draft': 'पुढे — मसुदा तयार करा',
      'btn_submit_claim': 'दावा सादर करा',
      'msg_draft_saved': '✅ मसुदा जतन झाला',
      'msg_ai_generating': 'AI मसुदा तयार करत आहे…',
      'claim_status_draft': 'मसुदा',
      'claim_status_submitted': 'सादर',
      'claim_status_under_review': 'पुनरावलोकन',
      'claim_status_approved': 'मंजूर',
      'claim_status_appeal': 'अपील दाखल',
      // Common Home Keys
      'welcome': 'नमस्कार',
      'villager': 'ग्रामस्थ',
      'approved_claims': 'मंजूर दावे',
      'hectares': 'हेक्टर क्षेत्र',
      'meeting_records': 'सभा नोंदी',
      'claims': 'दावे (Claims)',
      'action_new_claim_sub': 'Submit new individual or community claim',
      'coming_soon': 'लवकरच येत आहे (Coming Soon)',
      'action_evidence_checklist': 'पुरावा चेकलिस्ट (Rule 13)',
      'action_evidence_checklist_sub': 'View required documents and evidence',
      'gram_sabha': 'ग्रामसभा (Gram Sabha)',
      'action_view_records': 'ग्रामसभा नोंदी पहा',
      'action_view_records_sub': 'View Gram Sabha Records & Ledger',
      'action_self_checkin': 'स्वयं-नोंदणी (Self Check-in)',
      'action_self_checkin_sub': 'Mark attendance for ongoing meeting',
      'select_active_meeting_first': 'Please select an active meeting from the dashboard first.',
      'action_map': 'वनसीमा नकाशा',
      'action_map_sub': 'View Forest Boundary Map',
      'action_know_rights': 'आपले हक्क जाणा (FRA)',
      'action_know_rights_sub': 'Know Your Rights — Forest Rights Act',
      'todays_meeting': 'आजची ग्रामसभा',
      'next_meeting': 'पुढील ग्रामसभा',
      'venue': 'स्थळ',
      'mark_attendance': 'माझी उपस्थिती नोंदवा →',
      'no_meeting_scheduled': 'कोणतीही सभा निश्चित नाही',
      'admin_welcome': 'वनमित्र Admin',
      'admin_subtitle': 'ग्रामसभा प्रशासक',
      'total_claims': 'एकूण दावे',
      'meetings': 'सभा',
      'resolutions': 'ठराव',
      'members': 'सदस्य',
      // My Claims Screen
      'search_claim_hint': 'अर्ज क्रमांकाने शोधा / Search by Claim ID...',
      'filter_all': 'सर्व',
      'filter_approved': 'मंजूर',
      'filter_pending': 'प्रलंबित',
      'filter_rejected': 'नामंजूर',
      'claims_count_suffix': 'दावे',
      'appeal_deadline': 'अपील मुदत',
      'days_left': 'दिवस शिल्लक',
      'appeal_now': 'अपील करा →',
      'application_no': 'अर्ज क्र.',
      'survey_no': 'सर्वे',
      'sq_meters': 'चौ.मी.',
      'date_prefix': 'दिनांक',
      'step_received': 'प्राप्त',
      'step_verification': 'पडताळणी',
      'step_gramsabha': 'ग्रामसभा',
      'step_decision': 'निर्णय',
      'no_claims_filter': 'या फिल्टरसाठी कोणतेही दावे नाहीत.',
      'no_claims_yet': 'अद्याप कोणताही दावा दाखल नाही.',
      'search_placeholder': 'अर्ज क्रमांक किंवा दावेदाराने शोधा',
      'error_loading_claims': 'दावे लोड करता आले नाहीत. कृपया आपले कनेक्शन तपासा.',
      // Claim Type Screen
      'claim_type': 'दावा प्रकार',
      'eligibility_check': 'पात्रता तपासणी (FRA Sec. 2)',
      'st_question': 'आपण अनुसूचित जमाती (ST) मध्ये आहात का?',
      'yes': 'होय',
      'no': 'नाही',
      'residence_year': 'जमिनीवर वास्तव्य/शेती सुरू झाल्याचे वर्ष:',
      'date_hint': 'उदा. 1995-01-01 (YYYY-MM-DD)',
      'eligible_fdst': '✅ पात्र — FDST (अनुसूचित जमाती) श्रेणी',
      'eligible_otfd': '✅ पात्र — OTFD श्रेणी',
      'not_eligible': '❌ 13 डिसेंबर 2005 पूर्वी वास्तव्य आवश्यक आहे.',
      'select_claim_type': 'दावा प्रकार निवडा',
      'select_claim_type_sub': 'Select the type of claim you want to file',
      'form_a_desc': 'FRA कलम 3(1)(अ) अंतर्गत वैयक्तिक वन हक्क किंवा कलम 3(1)(ब-ड) अंतर्गत सामुदायिक हक्क.',
      'form_b_desc': 'FRA कलम 3(1)(ई) अंतर्गत सामुदायिक वन संसाधन हक्क (CFR). ग्रामसभेने दाखल करावे.',
      'fra_info': 'कोणता फॉर्म भरावा हे जाणून घेण्यासाठी वन हक्क कायदा 2006 पहा.',
      'recommended': 'शिफारस केलेले',
      // Evidence Checklist Screen
      'breadcrumbs_evidence': 'पुरावा',
      'upload_offline_error': 'ऑफलाइन — पुढे अपलोड करा.',
      'upload_verified': '✅ पडताळणी झाली!',
      'upload_review': '⚠️ पुनरावलोकन आवश्यक',
      'upload_rejected': '❌ नाकारले — पुन्हा प्रयत्न करा',
      'match': 'सामना',
      'evidence_category': 'पुरावा श्रेणी',
      'evidence_weight': 'वजन',
      'evidence_status': 'स्थिती',
      'evidence_unverified': 'तपासले नाही',
      'evidence_rule_13_note': 'नियम 13 (FRA Rules 2008): मौखिक पुरावा, वडीलधाऱ्यांचे निवेदन आणि सामुदायिक पडताळणी स्वीकारली जाते.',
      'btn_next_incomplete': 'पुढे — पुरावे पूर्ण नाहीत',
      'btn_more_evidence_needed': 'अधिक पुरावे आवश्यक',
      // Evidence Gauge
      'evidence_ready': '🟢 तयार — सादर करा',
      'evidence_partial': '🟡 अपूर्ण — पुरावे जोडा',
      'evidence_risk': '🔴 उच्च धोका — FRC शी संपर्क करा',
      'evidence_score_label': 'पुरावा स्कोर (E = Σwᵢ·xᵢ)',
      'evidence_submitted': 'पुरावे सादर',
      'evidence_upload_pending': '🔘 अपलोड करणे बाकी',
      'evidence_btn_upload': 'अपलोड',
      'evidence_verified_chip': '✅ पडताळणी झाली',
      'evidence_review_chip': '⚠️ पुनरावलोकन',
      'evidence_rejected_chip': '❌ नाकारले',
      // Evidence Categories
      'ev_cat_government_records': 'शासकीय नोंदी (मतदार ओळखपत्र, रेशनकार्ड, जमीन नोंदी)',
      'ev_cat_physical_structures': 'भौतिक संरचना (विहिरी, बांध, जमिनीवरील घरे)',
      'ev_cat_satellite_imagery': 'उपग्रह/हवाई छायाचित्रे',
      'ev_cat_elder_statements': 'वडीलधाऱ्यांचे निवेदन (किमान 2 शेजारी)',
      'ev_cat_traditional_structures': 'पारंपारिक सामुदायिक संरचना (पवित्र वनखंड, दफनभूमी)',
      'ev_cat_other_govt_schemes': 'इतर शासकीय योजना पुरावे (मनरेगा जॉबकार्ड)',
      'ev_desc_government_records': '१३ डिसेंबर २००५ पूर्वी अस्तित्वात किंवा वास्तव्यास असल्याचे सिद्ध करणारी कोणतीही अधिकृत शासकीय नोंद.',
      'ev_desc_physical_structures': 'दावा केलेल्या जमिनीवरील भौतिक किंवा कृषी सुधारणांचा पुरावा (उदा. विहीर, बांध).',
      'ev_desc_satellite_imagery': 'जमिनीवरील ऐतिहासिक लागवड किंवा ताब्याचा दृश्य पुरावा.',
      'ev_desc_elder_statements': 'दावेदाराच्या दीर्घकालीन ताब्याची पुष्टी करणारे किमान २ गावकरी किंवा शेजाऱ्यांचे निवेदन.',
      'ev_desc_traditional_structures': 'जमिनीवर किंवा जवळील पारंपारिक सामुदायिक खुणा किंवा वास्तूंचा पुरावा.',
      'ev_desc_other_govt_schemes': 'दावेदार आणि जमिनीशी जोडलेल्या शासकीय योजना नोंदणीचा पुरावा.',
      'rule13_title': 'नियम १३ पुरावा यादी',
      'rule13_subtitle': 'वन हक्क कायदा (FRA) नियम १३ नुसार, दावेदारांनी "पुरावा पूर्णता स्कोअर" तयार करण्यासाठी या कागदपत्रांचे संयोजन प्रदान करणे आवश्यक आहे. ग्रामसभेच्या मान्यतेसाठी ८०% किंवा त्याहून अधिक स्कोअर आवश्यक आहे.',
      'rule13_official_link': 'अधिकृत FRA मार्गदर्शक तत्त्वे पहा',
      // Portal
      'footer_text': 'हेल्पलाइन: 1800-209-6060 | वन हक्क कायदा 2006 | गोपनीयता धोरण',
      'app_title': 'VanMitra-AI | वनमित्र',
      'default_village_name': 'ओझर ग्रामपंचायत, जव्हार',
      // Claim Form Screen
      'step_1_claimant': '① दावेदार',
      'step_2_land': '② जमीन',
      'step_3_occupancy': '③ ताबा',
      'step_4_evidence': '④ पुरावा',
      'step_5_review': '⑤ पुनरावलोकन',
      'draft_saved': '✅ मसुदा जतन झाला',
      'form_a_title': 'फॉर्म अ — वैयक्तिक दावा',
      'form_b_title': 'फॉर्म ब — सामुदायिक दावा',
      'section_claimant_info': 'दावेदार माहिती',
      'section_land_details': 'जमीन तपशील',
      'section_occupancy_details': 'ताबा तपशील',
      'section_upload_evidence': 'पुरावा अपलोड करा',
      'label_claimant_name': 'दावेदाराचे नाव *',
      'hint_claimant_name': 'पूर्ण नाव मराठीत / Full name',
      'label_father_name': 'वडिलांचे / पतीचे नाव *',
      'hint_father_name': 'Father\'s / Husband\'s name',
      'label_address': 'पत्ता *',
      'hint_address': 'गाव, तालुका, जिल्हा',
      'info_auto_fill': 'जव्हार तालुका, पालघर जिल्हा हे आपोआप भरले जाईल.',
      'label_survey_no': 'सर्वे / गट नंबर',
      'hint_survey_no': 'उदा. 123/4A',
      'label_area': 'क्षेत्र (चौ.मी.) *',
      'hint_area': 'उदा. 1200',
      'label_nature_of_claim': 'हक्काचे स्वरूप *',
      'label_years_occupied': 'किती वर्षांपासून ताबा आहे? *',
      'hint_years_occupied': 'उदा. 30',
      'label_before_2005': '13 डिसेंबर 2005 पूर्वी ताबा होता (FRA अट)',
      'label_land_description': 'जमिनीचे वर्णन',
      'hint_land_description': 'वापर, सीमा, खुणा',
      'fra_2005_warning': 'FRA 2006 नुसार, 13 डिसेंबर 2005 पूर्वी ताबा असणे आवश्यक आहे.',
      'evidence_upload_instruction': 'पुढील स्क्रीनवर सर्व 6 पुरावा श्रेण्या अपलोड करा आणि AI पडताळणी करा.',
      'btn_go_to_evidence': 'पुरावा पडताळणी स्क्रीनवर जा',
      'section_review_submit': 'पुनरावलोकन व सादर',
      'review_submit_desc': 'AI-निर्मित मसुदा तपासा. मान्य केल्यावर ग्रामसभेला सादर केला जाईल.',
      'btn_preview_draft': 'मसुदा पूर्वावलोकन',
      'btn_save': 'जतन',
      'btn_back': 'मागे',
      'btn_next': 'पुढे',
    },
    'hi': {
      'language_title': 'भाषा चुनें',
      'language_subtitle': 'अपनी पसंदीदा भाषा चुनें',
      'btn_continue': 'आगे बढ़ें →',
      'login_title': 'लॉग इन करें',
      'login_subtitle': 'VanMitra-AI में साइन इन करें',
      'label_name': 'आपका नाम',
      'hint_name': 'अपना पूरा नाम दर्ज करें',
      'label_phone': 'मोबाइल नंबर',
      'hint_phone': '10 अंकों का मोबाइल नंबर',
      'label_role': 'भूमिका चुनें',
      'role_villager': 'ग्रामीण (Villager)',
      'role_admin': 'ग्राम पंचायत (Admin)',
      'label_village': 'गांव चुनें',
      'btn_send_otp': 'OTP भेजें →',
      'label_otp': 'OTP कोड',
      'btn_verify': 'सत्यापित करें और आगे बढ़ें →',
      'legal_notice': 'आपका डेटा आपके डिवाइस पर स्थानीय रूप से सहेजा जाता है। आपकी सहमति के बिना कोई व्यक्तिगत जानकारी साझा नहीं की जाती है।',
      'claim_nature_cultivation': 'खेती',
      'claim_nature_habitation': 'आवास',
      'claim_nature_mfpCollection': 'MFP संग्रह',
      'claim_nature_grazing': 'चराई',
      'claim_nature_waterBodies': 'जल निकाय',
      'claim_nature_traditionalResource': 'पारंपरिक संसाधन',
      'claim_nature_other': 'अन्य',
      // Dashboard & Tabs
      'tab_dashboard': 'डैशबोर्ड',
      'tab_claims': 'दावे',
      'tab_gramsabha': 'ग्राम सभा',
      'tab_map': 'नक्शा',
      'tab_profile': 'प्रोफ़ाइल',
      'tab_upcoming': 'आगामी (Upcoming)',
      'tab_past': 'पिछला (Past)',
      // Actions
      'action_new_claim': 'नया दावा दर्ज करें',
      'action_track_claim': 'मेरे दावे ट्रैक करें',
      'action_schedule_meeting': 'बैठक तय करें',
      'action_post_notice': 'सूचना पोस्ट करें',
      'action_attendance': 'उपस्थिति',
      'action_record_resolution': 'प्रस्ताव दर्ज करें',
      'action_verify_chain': 'चेन सत्यापन',
      'action_review_claims': 'दावों की समीक्षा करें',
      'action_map_monitor': 'सीमा निगरानी',
      // Claims
      'title_new_claim': 'नया दावा',
      'title_draft_preview': 'ड्राफ्ट पूर्वावलोकन',
      'title_evidence_checklist': 'सबूत जांच सूची',
      'title_appeal_draft': 'अपील ड्राफ्ट',
      'title_rejection_analysis': 'अस्वीकृति विश्लेषण',
      'title_my_claims': 'मेरे दावे',
      'btn_next_draft': 'आगे — ड्राफ्ट बनाएं',
      'btn_submit_claim': 'दावा प्रस्तुत करें',
      'msg_draft_saved': '✅ ड्राफ्ट सहेजा गया',
      'msg_ai_generating': 'AI ड्राफ्ट बना रहा है...',
      'claim_status_draft': 'ड्राफ्ट',
      'claim_status_submitted': 'प्रस्तुत',
      'claim_status_under_review': 'समीक्षा के तहत',
      'claim_status_approved': 'मंजूर',
      'claim_status_appeal': 'अपील दायर',
      // Common Home Keys
      'welcome': 'नमस्ते',
      'villager': 'ग्रामीण',
      'approved_claims': 'मंजूर दावे',
      'hectares': 'हेक्टेयर क्षेत्र',
      'meeting_records': 'बैठक रिकॉर्ड',
      'claims': 'दावे (Claims)',
      'action_new_claim_sub': 'नया व्यक्तिगत या सामुदायिक दावा प्रस्तुत करें',
      'coming_soon': 'जल्द आ रहा है (Coming Soon)',
      'action_evidence_checklist': 'सबूत चेकलिस्ट (Rule 13)',
      'action_evidence_checklist_sub': 'आवश्यक दस्तावेज और सबूत देखें',
      'gram_sabha': 'ग्राम सभा',
      'action_view_records': 'ग्राम सभा रिकॉर्ड देखें',
      'action_view_records_sub': 'ग्राम सभा रिकॉर्ड और लेजर देखें',
      'action_self_checkin': 'स्व-चेक इन',
      'action_self_checkin_sub': 'बैठक के लिए उपस्थिति दर्ज करें',
      'select_active_meeting_first': 'कृपया डैशबोर्ड से सक्रिय बैठक चुनें।',
      'action_map': 'वन सीमा मानचित्र',
      'action_map_sub': 'वन सीमा मानचित्र देखें',
      'action_know_rights': 'अपने अधिकार जानें (FRA)',
      'action_know_rights_sub': 'अपने अधिकार जानें — वन अधिकार अधिनियम',
      'todays_meeting': 'आज की बैठक',
      'next_meeting': 'अगली बैठक',
      'venue': 'स्थान',
      'mark_attendance': 'मेरी उपस्थिति दर्ज करें →',
      'no_meeting_scheduled': 'कोई बैठक निर्धारित नहीं है',
      'admin_welcome': 'वनमित्र Admin',
      'admin_subtitle': 'ग्राम सभा प्रशासक',
      'total_claims': 'कुल दावे',
      'meetings': 'बैठकें',
      'resolutions': 'प्रस्ताव',
      'members': 'सदस्य',
      // My Claims Screen
      'search_claim_hint': 'दावा आईडी से खोजें...',
      'filter_all': 'सभी',
      'filter_approved': 'मंजूर',
      'filter_pending': 'लंबित',
      'filter_rejected': 'अस्वीकृत',
      'claims_count_suffix': 'दावे',
      'appeal_deadline': 'अपील की समय सीमा',
      'days_left': 'दिन शेष',
      'appeal_now': 'अपील करें →',
      'application_no': 'आवेदन संख्या',
      'survey_no': 'सर्वेक्षण',
      'sq_meters': 'वर्ग मी.',
      'date_prefix': 'दिनांक',
      'step_received': 'प्राप्त',
      'step_verification': 'सत्यापन',
      'step_gramsabha': 'ग्राम सभा',
      'step_decision': 'निर्णय',
      'no_claims_filter': 'इस फ़िल्टर से कोई दावा मेल नहीं खाता।',
      'no_claims_yet': 'अभी तक कोई दावा दर्ज नहीं किया गया है।',
      'search_placeholder': 'आवेदन संख्या या दावेदार से खोजें',
      'error_loading_claims': 'दावे लोड नहीं हो सके। कृपया अपना कनेक्शन जांचें।',
      // Claim Type Screen
      'claim_type': 'दावा का प्रकार',
      'eligibility_check': 'पात्रता की जांच (FRA Sec. 2)',
      'st_question': 'क्या आप अनुसूचित जनजाति (ST) से हैं?',
      'yes': 'हाँ',
      'no': 'नहीं',
      'residence_year': 'भूमि पर निवास/खेती शुरू होने का वर्ष:',
      'date_hint': 'उदा. 1995-01-01 (YYYY-MM-DD)',
      'eligible_fdst': '✅ पात्र — FDST (अनुसूचित जनजाति) श्रेणी',
      'eligible_otfd': '✅ पात्र — OTFD श्रेणी',
      'not_eligible': '❌ 13 दिसंबर 2005 से पहले निवास आवश्यक है।',
      'select_claim_type': 'दावा का प्रकार चुनें',
      'select_claim_type_sub': 'Select the type of claim you want to file',
      'form_a_desc': 'FRA धारा 3(1)(a) के तहत व्यक्तिगत वन अधिकार या धारा 3(1)(b-d) के तहत सामुदायिक अधिकार।',
      'form_b_desc': 'FRA धारा 3(1)(i) के तहत सामुदायिक वन संसाधन (CFR)। ग्राम सभा द्वारा दायर।',
      'fra_info': 'कौन सा फॉर्म भरना है, यह जानने के लिए वन अधिकार अधिनियम 2006 देखें।',
      'recommended': 'अनुशंसित',
      // Evidence Checklist Screen
      'breadcrumbs_evidence': 'सबूत',
      'upload_offline_error': 'ऑफ़लाइन — बाद में अपलोड करें।',
      'upload_verified': '✅ सत्यापित!',
      'upload_review': '⚠️ समीक्षा की आवश्यकता है',
      'upload_rejected': '❌ अस्वीकृत — पुनः प्रयास करें',
      'match': 'मेल',
      'evidence_category': 'सबूत श्रेणी',
      'evidence_weight': 'वजन',
      'evidence_status': 'स्थिति',
      'evidence_unverified': 'असत्यापित',
      'evidence_rule_13_note': 'नियम 13 (FRA नियम 2008): मौखिक साक्ष्य, बुजुर्गों का बयान और सामुदायिक सत्यापन स्वीकार्य हैं।',
      'btn_next_incomplete': 'आगे — सबूत अधूरे हैं',
      'btn_more_evidence_needed': 'और सबूत की आवश्यकता है',
      // Evidence Gauge
      'evidence_ready': '🟢 तैयार — सबमिट करें',
      'evidence_partial': '🟡 आंशिक — सबूत जोड़ें',
      'evidence_risk': '🔴 उच्च जोखिम — FRC से संपर्क करें',
      'evidence_score_label': 'सबूत स्कोर (E = Σwᵢ·xᵢ)',
      'evidence_submitted': 'सबूत प्रस्तुत किए गए',
      'evidence_upload_pending': '🔘 अपलोड होना बाकी है',
      'evidence_btn_upload': 'अपलोड',
      'evidence_verified_chip': '✅ सत्यापित',
      'evidence_review_chip': '⚠️ समीक्षा',
      'evidence_rejected_chip': '❌ अस्वीकृत',
      // Evidence Categories
      'ev_cat_government_records': 'सरकारी रिकॉर्ड (मतदाता पहचान पत्र, राशन कार्ड, भूमि रिकॉर्ड)',
      'ev_cat_physical_structures': 'भौतिक संरचनाएं (कुएं, बांध, भूमि पर घर)',
      'ev_cat_satellite_imagery': 'उपग्रह/हवाई इमेजरी',
      'ev_cat_elder_statements': 'बुजुर्गों के बयान (कम से कम 2 पड़ोसी)',
      'ev_cat_traditional_structures': 'पारंपरिक सामुदायिक संरचनाएं (पवित्र उपवन, दफन स्थल)',
      'ev_cat_other_govt_schemes': 'अन्य सरकारी योजना साक्ष्य (मनरेगा जॉब कार्ड)',
      'ev_desc_government_records': '13 दिसंबर 2005 से पहले अस्तित्व या निवास साबित करने वाली कोई भी आधिकारिक सरकारी रजिस्ट्री।',
      'ev_desc_physical_structures': 'दावे वाली भूमि पर किए गए भौतिक या कृषि सुधारों का प्रमाण।',
      'ev_desc_satellite_imagery': 'भूमि की ऐतिहासिक खेती या कब्जे को दर्शाने वाला दृश्य प्रमाण।',
      'ev_desc_elder_statements': 'दावेदार के दीर्घकालिक कब्जे की पुष्टि करने वाले कम से कम 2 गांव के बुजुर्गों या पड़ोसियों के बयान।',
      'ev_desc_traditional_structures': 'भूमि पर या उसके पास पारंपरिक सामुदायिक स्थलों का प्रमाण।',
      'ev_desc_other_govt_schemes': 'दावेदार और भूमि से जुड़े सरकारी योजना नामांकन का प्रमाण।',
      'rule13_title': 'नियम 13 साक्ष्य सूची',
      'rule13_subtitle': 'वन अधिकार अधिनियम (FRA) नियम 13 के आधार पर, दावेदारों को "साक्ष्य पूर्णता स्कोर" बनाने के लिए इन दस्तावेजों का संयोजन प्रदान करना होगा। ग्राम सभा की मंजूरी के लिए 80% या उससे अधिक स्कोर की आवश्यकता है।',
      'rule13_official_link': 'आधिकारिक FRA दिशानिर्देश देखें',
      // Portal
      'footer_text': 'हेल्पलाइन: 1800-209-6060 | वन अधिकार अधिनियम 2006 | गोपनीयता नीति',
      'app_title': 'VanMitra-AI | वनमित्र',
      'default_village_name': 'ओझर ग्रामपंचायत, जव्हार',
      // Claim Form Screen
      'step_1_claimant': '① दावेदार',
      'step_2_land': '② भूमि',
      'step_3_occupancy': '③ कब्ज़ा',
      'step_4_evidence': '④ सबूत',
      'step_5_review': '⑤ समीक्षा',
      'draft_saved': '✅ ड्राफ्ट सहेजा गया',
      'form_a_title': 'फॉर्म ए — व्यक्तिगत दावा',
      'form_b_title': 'फॉर्म बी — सामुदायिक दावा',
      'section_claimant_info': 'दावेदार की जानकारी',
      'section_land_details': 'भूमि का विवरण',
      'section_occupancy_details': 'कब्ज़ा का विवरण',
      'section_upload_evidence': 'सबूत अपलोड करें',
      'label_claimant_name': 'दावेदार का नाम *',
      'hint_claimant_name': 'पूरा नाम',
      'label_father_name': 'पिता / पति का नाम *',
      'hint_father_name': 'पिता / पति का नाम',
      'label_address': 'पता *',
      'hint_address': 'गांव, तालुका, जिला',
      'info_auto_fill': 'जवाहर तालुका, पालघर जिला अपने आप भर जाएगा।',
      'label_survey_no': 'सर्वे / गट नंबर',
      'hint_survey_no': 'उदा. 123/4A',
      'label_area': 'क्षेत्र (वर्ग मीटर) *',
      'hint_area': 'उदा. 1200',
      'label_nature_of_claim': 'अधिकार की प्रकृति *',
      'label_years_occupied': 'कितने वर्षों से कब्ज़ा है? *',
      'hint_years_occupied': 'उदा. 30',
      'label_before_2005': '13 दिसंबर 2005 से पहले कब्ज़ा (FRA शर्त)',
      'label_land_description': 'भूमि का विवरण',
      'hint_land_description': 'उपयोग, सीमाएं, स्थलचिह्न',
      'fra_2005_warning': 'FRA 2006 के अनुसार, 13 दिसंबर 2005 से पहले कब्ज़ा अनिवार्य है।',
      'evidence_upload_instruction': 'अगली स्क्रीन पर सभी 6 साक्ष्य श्रेणियां अपलोड करें और AI सत्यापन करें।',
      'btn_go_to_evidence': 'सबूत सत्यापन स्क्रीन पर जाएं',
      'section_review_submit': 'समीक्षा और सबमिट करें',
      'review_submit_desc': 'AI-जनरेट किए गए ड्राफ्ट की समीक्षा करें। स्वीकृत होने पर ग्राम सभा को प्रस्तुत किया जाएगा।',
      'btn_preview_draft': 'ड्राफ्ट का पूर्वावलोकन करें',
      'btn_save': 'सहेजें',
      'btn_back': 'पीछे',
      'btn_next': 'आगे',
    },
    'kn': {
      'language_title': 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
      'language_subtitle': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'btn_continue': 'ಮುಂದುವರೆಯಿರಿ →',
      'login_title': 'ಲಾಗಿನ್ ಮಾಡಿ',
      'login_subtitle': 'VanMitra-AI ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'label_name': 'ನಿಮ್ಮ ಹೆಸರು',
      'hint_name': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'label_phone': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'hint_phone': '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'label_role': 'ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'role_villager': 'ಹಳ್ಳಿಗ (Villager)',
      'role_admin': 'ಗ್ರಾಮ ಪಂಚಾಯತ್ (Admin)',
      'label_village': 'ಗ್ರಾಮವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'btn_send_otp': 'OTP ಕಳುಹಿಸಿ →',
      'label_otp': 'OTP ಕೋಡ್',
      'btn_verify': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರೆಯಿರಿ →',
      'legal_notice': 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಸ್ಥಳೀಯವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ. ನಿಮ್ಮ ಒಪ್ಪಿಗೆಯಿಲ್ಲದೆ ಯಾವುದೇ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳಲಾಗುವುದಿಲ್ಲ.',
    }
  };

  String translate(String key) {
    final langCode = locale.languageCode;
    if (_localizedValues.containsKey(langCode) && _localizedValues[langCode]!.containsKey(key)) {
      return _localizedValues[langCode]![key]!;
    }
    return _localizedValues['en']![key] ?? key;
  }

  // Legacy getters for onboarding screens
  String get languageTitle => translate('language_title');
  String get languageSubtitle => translate('language_subtitle');
  String get btnContinue => translate('btn_continue');
  String get loginTitle => translate('login_title');
  String get loginSubtitle => translate('login_subtitle');
  String get labelName => translate('label_name');
  String get hintName => translate('hint_name');
  String get labelPhone => translate('label_phone');
  String get hintPhone => translate('hint_phone');
  String? get labelRole => translate('label_role');
  String? get roleVillager => translate('role_villager');
  String? get roleAdmin => translate('role_admin');
  String? get labelVillage => translate('label_village');
  String get btnSendOtp => translate('btn_send_otp');
  String get labelOtp => translate('label_otp');
  String get btnVerify => translate('btn_verify');
  String get legalNotice => translate('legal_notice');
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'mr', 'hi', 'kn'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
